AWSTemplateFormatVersion: '2010-09-09'
Description: 'Dalton AWS Integration StackSet - Creates an IAM role with read-only access to selected AWS services for multi-account Organizations deployment'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required Configuration
        Parameters:
          - ExternalId
      - Label:
          default: Full Account Access
        Parameters:
          - EnableFullAccess
      - Label:
          default: Compute Services
        Parameters:
          - EnableEC2
          - EnableLambda
          - EnableECS
      - Label:
          default: Storage & Database Services
        Parameters:
          - EnableS3
          - EnableRDS
          - EnableDynamoDB
      - Label:
          default: Monitoring Services
        Parameters:
          - EnableCloudWatch
      - Label:
          default: Messaging & Networking Services
        Parameters:
          - EnableSNS
          - EnableSQS
          - EnableRoute53
      - Label:
          default: Security Services
        Parameters:
          - EnableSecretsManager

Parameters:
  ExternalId:
    Type: String
    Description: External ID for secure cross-account access (generated by Dalton - do not change)
    MinLength: 1
    AllowedPattern: '.+'
    ConstraintDescription: ExternalId is required and cannot be empty

  EnableFullAccess:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Grant full read-only access to ALL AWS services using AWS managed ReadOnlyAccess policy (overrides individual service selections)

  EnableS3:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to Amazon S3

  EnableRDS:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to Amazon RDS

  EnableEC2:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to Amazon EC2

  EnableLambda:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to AWS Lambda

  EnableCloudWatch:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to Amazon CloudWatch (Logs and Metrics)

  EnableDynamoDB:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to Amazon DynamoDB

  EnableECS:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to Amazon ECS

  EnableSNS:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to Amazon SNS

  EnableSQS:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to Amazon SQS

  EnableSecretsManager:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to AWS Secrets Manager (metadata only, not secret values)

  EnableRoute53:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable read-only access to Amazon Route 53

Conditions:
  FullAccessEnabled: !Equals [!Ref EnableFullAccess, 'true']
  NotFullAccess: !Not [!Equals [!Ref EnableFullAccess, 'true']]
  # Individual service conditions - only apply when NOT using full access
  S3Enabled: !And [!Equals [!Ref EnableS3, 'true'], !Condition NotFullAccess]
  RDSEnabled: !And [!Equals [!Ref EnableRDS, 'true'], !Condition NotFullAccess]
  EC2Enabled: !And [!Equals [!Ref EnableEC2, 'true'], !Condition NotFullAccess]
  LambdaEnabled: !And [!Equals [!Ref EnableLambda, 'true'], !Condition NotFullAccess]
  CloudWatchEnabled: !And [!Equals [!Ref EnableCloudWatch, 'true'], !Condition NotFullAccess]
  DynamoDBEnabled: !And [!Equals [!Ref EnableDynamoDB, 'true'], !Condition NotFullAccess]
  ECSEnabled: !And [!Equals [!Ref EnableECS, 'true'], !Condition NotFullAccess]
  SNSEnabled: !And [!Equals [!Ref EnableSNS, 'true'], !Condition NotFullAccess]
  SQSEnabled: !And [!Equals [!Ref EnableSQS, 'true'], !Condition NotFullAccess]
  SecretsManagerEnabled: !And [!Equals [!Ref EnableSecretsManager, 'true'], !Condition NotFullAccess]
  Route53Enabled: !And [!Equals [!Ref EnableRoute53, 'true'], !Condition NotFullAccess]

Resources:
  # IAM Role with fixed name for consistency across all accounts in the organization
  DaltonAWSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'Dalton-AWS-Viewer'
      Description: 'IAM role for Dalton AWS integration with read-only access (deployed via StackSet)'
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::767398131998:role/DaltonIntegrationsRole'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      # Attach AWS managed ReadOnlyAccess policy when Full Access is enabled
      ManagedPolicyArns: !If
        - FullAccessEnabled
        - - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
        - !Ref 'AWS::NoValue'
      Tags:
        - Key: ManagedBy
          Value: Dalton
        - Key: Purpose
          Value: AWS-Integration
        - Key: DeploymentMethod
          Value: StackSet

  # Deny policy for sensitive values (applied when Full Access is enabled)
  # This overrides the ReadOnlyAccess policy to prevent reading secret values
  FullAccessDenySecretsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: FullAccessEnabled
    Properties:
      ManagedPolicyName: 'Dalton-DenySecretValues'
      Description: 'Deny access to secret/sensitive values (safety net for ReadOnlyAccess policy)'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenySecretValues
            Effect: Deny
            Action:
              - 'secretsmanager:GetSecretValue'
              - 'ssm:GetParameter'
              - 'ssm:GetParameters'
              - 'ssm:GetParametersByPath'
            Resource: '*'

  # S3 Read-Only Policy
  S3ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: S3Enabled
    Properties:
      ManagedPolicyName: 'Dalton-S3-ReadOnly'
      Description: 'Read-only access to S3 for Dalton'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3ReadOnly
            Effect: Allow
            Action:
              - 's3:GetBucketLocation'
              - 's3:GetBucketTagging'
              - 's3:GetBucketVersioning'
              - 's3:GetBucketPolicy'
              - 's3:GetBucketAcl'
              - 's3:GetBucketCORS'
              - 's3:GetBucketEncryption'
              - 's3:GetBucketLogging'
              - 's3:GetBucketNotification'
              - 's3:GetBucketPublicAccessBlock'
              - 's3:GetObject'
              - 's3:GetObjectAcl'
              - 's3:GetObjectTagging'
              - 's3:GetObjectVersion'
              - 's3:ListBucket'
              - 's3:ListAllMyBuckets'
              - 's3:ListBucketVersions'
            Resource: '*'

  # RDS Read-Only Policy
  RDSReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: RDSEnabled
    Properties:
      ManagedPolicyName: 'Dalton-RDS-ReadOnly'
      Description: 'Read-only access to RDS for Dalton'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: RDSReadOnly
            Effect: Allow
            Action:
              - 'rds:Describe*'
              - 'rds:ListTagsForResource'
              - 'rds:DownloadDBLogFilePortion'
            Resource: '*'

  # EC2 Read-Only Policy
  EC2ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: EC2Enabled
    Properties:
      ManagedPolicyName: 'Dalton-EC2-ReadOnly'
      Description: 'Read-only access to EC2 for Dalton'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EC2ReadOnly
            Effect: Allow
            Action:
              - 'ec2:Describe*'
              - 'ec2:GetConsoleOutput'
              - 'ec2:GetConsoleScreenshot'
            Resource: '*'

  # Lambda Read-Only Policy
  LambdaReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: LambdaEnabled
    Properties:
      ManagedPolicyName: 'Dalton-Lambda-ReadOnly'
      Description: 'Read-only access to Lambda for Dalton'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: LambdaReadOnly
            Effect: Allow
            Action:
              - 'lambda:GetFunction'
              - 'lambda:GetFunctionConfiguration'
              - 'lambda:GetFunctionCodeSigningConfig'
              - 'lambda:GetFunctionEventInvokeConfig'
              - 'lambda:GetPolicy'
              - 'lambda:GetAlias'
              - 'lambda:ListFunctions'
              - 'lambda:ListAliases'
              - 'lambda:ListEventSourceMappings'
              - 'lambda:ListVersionsByFunction'
              - 'lambda:ListTags'
              - 'lambda:ListLayers'
              - 'lambda:ListLayerVersions'
            Resource: '*'

  # CloudWatch Read-Only Policy (Logs and Metrics)
  CloudWatchReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: CloudWatchEnabled
    Properties:
      ManagedPolicyName: 'Dalton-CloudWatch-ReadOnly'
      Description: 'Read-only access to CloudWatch Logs and Metrics for Dalton'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudWatchMetricsReadOnly
            Effect: Allow
            Action:
              - 'cloudwatch:Describe*'
              - 'cloudwatch:Get*'
              - 'cloudwatch:List*'
            Resource: '*'
          - Sid: CloudWatchLogsReadOnly
            Effect: Allow
            Action:
              - 'logs:Describe*'
              - 'logs:Get*'
              - 'logs:List*'
              - 'logs:FilterLogEvents'
              - 'logs:StartQuery'
              - 'logs:StopQuery'
              - 'logs:GetQueryResults'
            Resource: '*'

  # DynamoDB Read-Only Policy
  DynamoDBReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DynamoDBEnabled
    Properties:
      ManagedPolicyName: 'Dalton-DynamoDB-ReadOnly'
      Description: 'Read-only access to DynamoDB for Dalton'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DynamoDBReadOnly
            Effect: Allow
            Action:
              - 'dynamodb:DescribeTable'
              - 'dynamodb:DescribeTableReplicaAutoScaling'
              - 'dynamodb:DescribeTimeToLive'
              - 'dynamodb:DescribeContinuousBackups'
              - 'dynamodb:DescribeGlobalTable'
              - 'dynamodb:DescribeGlobalTableSettings'
              - 'dynamodb:DescribeLimits'
              - 'dynamodb:DescribeStream'
              - 'dynamodb:ListTables'
              - 'dynamodb:ListTagsOfResource'
              - 'dynamodb:ListStreams'
              - 'dynamodb:ListGlobalTables'
              - 'dynamodb:GetItem'
              - 'dynamodb:BatchGetItem'
              - 'dynamodb:Query'
              - 'dynamodb:Scan'
            Resource: '*'

  # ECS Read-Only Policy
  ECSReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: ECSEnabled
    Properties:
      ManagedPolicyName: 'Dalton-ECS-ReadOnly'
      Description: 'Read-only access to ECS for Dalton'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ECSReadOnly
            Effect: Allow
            Action:
              - 'ecs:Describe*'
              - 'ecs:List*'
            Resource: '*'

  # SNS Read-Only Policy
  SNSReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: SNSEnabled
    Properties:
      ManagedPolicyName: 'Dalton-SNS-ReadOnly'
      Description: 'Read-only access to SNS for Dalton'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SNSReadOnly
            Effect: Allow
            Action:
              - 'sns:GetTopicAttributes'
              - 'sns:GetSubscriptionAttributes'
              - 'sns:ListTopics'
              - 'sns:ListSubscriptions'
              - 'sns:ListSubscriptionsByTopic'
              - 'sns:ListTagsForResource'
            Resource: '*'

  # SQS Read-Only Policy
  SQSReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: SQSEnabled
    Properties:
      ManagedPolicyName: 'Dalton-SQS-ReadOnly'
      Description: 'Read-only access to SQS for Dalton'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SQSReadOnly
            Effect: Allow
            Action:
              - 'sqs:GetQueueAttributes'
              - 'sqs:GetQueueUrl'
              - 'sqs:ListQueues'
              - 'sqs:ListQueueTags'
              - 'sqs:ListDeadLetterSourceQueues'
            Resource: '*'

  # Secrets Manager Read-Only Policy (metadata only - no secret values)
  SecretsManagerReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: SecretsManagerEnabled
    Properties:
      ManagedPolicyName: 'Dalton-SecretsManager-ReadOnly'
      Description: 'Read-only access to Secrets Manager metadata for Dalton (does not include secret values)'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SecretsManagerMetadataOnly
            Effect: Allow
            Action:
              - 'secretsmanager:DescribeSecret'
              - 'secretsmanager:ListSecrets'
              - 'secretsmanager:GetResourcePolicy'
              - 'secretsmanager:ListSecretVersionIds'
            Resource: '*'
          - Sid: DenySecretValues
            Effect: Deny
            Action:
              - 'secretsmanager:GetSecretValue'
            Resource: '*'

  # Route 53 Read-Only Policy
  Route53ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: Route53Enabled
    Properties:
      ManagedPolicyName: 'Dalton-Route53-ReadOnly'
      Description: 'Read-only access to Route 53 for Dalton'
      Roles:
        - !Ref DaltonAWSRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Route53ReadOnly
            Effect: Allow
            Action:
              - 'route53:GetHostedZone'
              - 'route53:GetHealthCheck'
              - 'route53:GetHealthCheckStatus'
              - 'route53:GetDNSSEC'
              - 'route53:GetTrafficPolicy'
              - 'route53:ListHostedZones'
              - 'route53:ListHostedZonesByName'
              - 'route53:ListResourceRecordSets'
              - 'route53:ListHealthChecks'
              - 'route53:ListTagsForResource'
              - 'route53:ListTrafficPolicies'
              - 'route53:ListTrafficPolicyInstances'
              - 'route53:ListQueryLoggingConfigs'
            Resource: '*'

Outputs:
  RoleArn:
    Description: The ARN of the created IAM Role for Dalton
    Value: !GetAtt DaltonAWSRole.Arn

  RoleName:
    Description: The name of the created IAM Role
    Value: !Ref DaltonAWSRole

  AccountId:
    Description: The AWS Account ID where this role was created
    Value: !Ref AWS::AccountId

  ExternalId:
    Description: The External ID used for this integration
    Value: !Ref ExternalId
